name: Build Android APK (Simple)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-apk:
    runs-on: ubuntu-20.04  # Use Ubuntu 20.04 for better stability
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip \
          openjdk-8-jdk \
          python3-pip \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 \
          cmake libffi-dev libssl-dev \
          build-essential \
          python3-dev \
          python3-venv
        
    - name: Set JAVA_HOME
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV
        
    - name: Install Python dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install buildozer==1.5.0 cython==0.29.33
        
    - name: Use simplified buildozer.spec
      run: |
        cp buildozer.spec.simple buildozer.spec
        
    - name: Pre-configure Android SDK licenses
      run: |
        echo "=== Pre-configuring Android SDK licenses ==="
        
        # Create Android SDK directory structure
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        mkdir -p $ANDROID_HOME/licenses
        
        # Create license files manually (these are the standard Android SDK license hashes)
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
        echo "d975f751698a77b662f1254ddbeed3901e976f5a" > $ANDROID_HOME/licenses/android-sdk-license
        echo "33b6a2b64607f11b759f320ef9dff4ae5c47d97a" > $ANDROID_HOME/licenses/google-gdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/mips-android-sysimage-license
        
        # Create repositories.cfg
        mkdir -p ~/.android
        echo "### User Sources for Android SDK Manager" > ~/.android/repositories.cfg
        echo "count=0" >> ~/.android/repositories.cfg
        
        echo "✅ Android SDK licenses pre-configured"
        
    - name: Initialize buildozer
      run: |
        buildozer init || true
        
    - name: Clean previous builds
      run: |
        buildozer android clean || true
        
    - name: Build APK
      run: |
        echo "=== Starting buildozer build ==="
        
        # Set environment variables
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
        
        # Build with timeout
        timeout 1800 buildozer android debug -v
        
    - name: Verify APK creation
      run: |
        echo "=== Verifying APK creation ==="
        if [ -f bin/*.apk ]; then
          echo "✅ APK created successfully"
          ls -la bin/*.apk
          file bin/*.apk
        else
          echo "❌ No APK found"
          echo "=== Checking for APK files ==="
          find . -name "*.apk" -type f || echo "No APK files found"
        fi
        
    - name: Upload APK (if exists)
      uses: actions/upload-artifact@v4
      with:
        name: ltrconverter-apk
        path: bin/*.apk
        if-no-files-found: ignore
