name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev build-essential
        
    - name: Install Python dependencies
      run: |
        pip3 install buildozer cython
        
    - name: Check buildozer installation
      run: |
        buildozer --version
        buildozer --help
        
    - name: Initialize buildozer (if needed)
      run: |
        if [ ! -f "buildozer.spec" ]; then
          buildozer init
        fi
        
    - name: Show buildozer.spec content
      run: |
        echo "=== buildozer.spec content ==="
        cat buildozer.spec
        
    - name: Clean previous builds
      run: |
        buildozer android clean || true
        
    - name: Build APK with verbose output
      run: |
        buildozer android debug -v
      continue-on-error: true
      
    - name: Show build logs on failure
      if: failure()
      run: |
        echo "=== Build failed, showing logs ==="
        ls -la .buildozer/ || true
        cat .buildozer/android/platform/build-*/logs/*.log || true
        
    - name: Check for APK files
      run: |
        echo "=== Checking for APK files ==="
        ls -la bin/ || echo "bin/ directory not found"
        find . -name "*.apk" -type f || echo "No APK files found"
        
    - name: Upload APK (if exists)
      uses: actions/upload-artifact@v4
      with:
        name: ltrconverter-apk
        path: bin/*.apk
        if-no-files-found: ignore
        
    - name: Create Release (if APK exists and has permissions)
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        if [ -f bin/*.apk ]; then
          echo "APK found, but skipping release creation due to permission issues"
          echo "Download the APK from the Artifacts section instead"
        else
          echo "No APK found to release"
        fi
